### ISSUE TITLE
What if you're not a mac user?

### ISSUE THREAD

**Issue by tatsujb** [erikphansen/vscode-toggle-column-selection#3]
In your guide you speak in mac so it makes no sense to me a linux/windows user.

shift + arrow works, obviously but then I don't understand when you say COMMAND-SHIFT-P
or OPTION-SHIFT-I. replacing ctrl with either command or option did not work. 

is this plugin simply mac only? 

If so, say so in big capital letters as the first line of your page here : https://marketplace.visualstudio.com/items?itemName=erikphansen.vscode-toggle-column-selection#overview

**Comment by erikphansen** [comment]
There's nothing about this extension that makes it Mac only. `ALT`-`SHIFT`-`I` should work as the default keybinding on Windows or Linux. I did update the README to make that clearer. I also removed the reference to the keybinding to open the VS Code Command Palette since that was unnecessary and varies depending on your system.

Also, I have no idea what Windows and Linux tools are comparable to Better Touch Tool, which is unfortunate because this extension is about a million times for useful when you can invoke it with a single tap of a modifier key.

Finally, I'm sorry that I didn't see this post until just now! I've adjusted my GitHub settings so that shouldn't happen again in the future.

Thanks,
Erik
